---
# Deployment for MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
    tier: application
spec:
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
        tier: application
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env: # The variables below could be set on a ConfigMap object
          - name : database__client
            value: mysql
          - name: database__connection__host
            value: mysql-service
          - name: database__connection__user
            value: ghostuser
          - name: database__connection__password
            value: "password"
          - name: database__connection__database
            value: ghost
          - name: url
            value: <IP>
          - name: mail__transport
            value: SMTP
          - name: mail__options__service
            value: Mailtrap
          - name: mail__options__host
            value: smtp.mailtrap.io
          - name: mail__options__port
            value: "2525"
          - name: mail__options__secure
            value: "false"
          - name: mail__options__auth__user
            value: <mail_user>
          - name: mail__options__auth__pass
            value: <mail_password>
        ports:
        - containerPort: <port>
